🐛 fix: fixed bug when use load_handlers function
Mistakenly detect __init__.py and __Pycache__ files and cause "AttributeError: module 'bot.__init__' has no attribute 'init'" error when run main.py